name: c-pointers-pres
services:
  - name: c-pointers-lecture
    github:
      repo: blainerothrock/c-pointers-pres
      branch: main
      deploy_on_push: true
    run_command: pnpm slidev --remote --port 8080
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 10
