name: c-pointers-pres
static_sites:
  - name: c-pointers-lecture
    github:
      repo: blainerothrock/c-pointers-pres
      branch: main
      deploy_on_push: true
    build_command: pnpm build
    output_dir: dist
    routes:
      - path: /
